do $$ begin if not exists (select from pg_roles where rolname=$q$anon$q$) then create role anon nologin; end if; if not exists (select from pg_roles where rolname=$q$authenticated$q$) then create role authenticated nologin; end if; if not exists (select from pg_roles where rolname=$q$service_role$q$) then create role service_role nologin bypassrls; end if; end $$;
grant usage on schema public to anon, authenticated;
create schema auth;
create table auth.users (id uuid primary key default gen_random_uuid(), email text, raw_user_meta_data jsonb default '{}'::jsonb);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
create schema storage;
create table storage.buckets (id text primary key, name text, public boolean);
create table storage.objects (id uuid default gen_random_uuid(), bucket_id text, name text);
alter table storage.objects enable row level security;
create function storage.foldername(name text) returns text[] language sql as $$ select string_to_array(name, '/') $$;
